### ISSUE TITLE
請求支援低解析度材質

### ISSUE THREAD

**Issue by asakuarus** [josh-hsu/JoshAutomationFX#6]

**Comment by josh-hsu** [comment]
將會支援更低解析度的模擬器，但仍不打算支援省電模式以及低解析度素材
請直接將模擬器的解析度調整成最低 1280x720

**Comment by josh-hsu** [comment]
已經完成此改良功能，請設定模擬器為 1280x720 並重啟
請用以下版本驗證: V0.50A 
下載: https://github.com/josh-hsu/JoshAutomationFX/raw/master/release/JoshAutomationFX.zip
說明: https://github.com/josh-hsu/JoshAutomationFX/
